/// Cien personas de prueba, con la forma exacta del modelo de identidad.
///
/// No es una lista de nombres: cada una trae lo que el SDK necesita para
/// demostrar las tres cosas que hay que poder probar sin un comercio real.
///
///   **alias** — cédula y correo. Son por los que se DIRECCIONA: únicos dentro
///   del comercio, y se puede enviar a cualquiera de los dos. Es lo que permite
///   probar «mandale a la cédula 12137717» sin saber su `userId`.
///
///   **atributos** — nombre, sucursal, ciudad y plan. Son para FILTRAR y
///   MOSTRAR, no para direccionar. Es lo que permite probar el envío segmentado
///   —«a todos los de CCS-01», «a los del plan Bronce»— y la búsqueda en la
///   consola.
///
/// Los datos están repartidos a propósito: ocho ciudades, tres sucursales en
/// cada una y cuatro planes, de modo que cualquier filtro devuelva un grupo de
/// tamaño razonable y no uno ni cien. Un juego de prueba donde todos comparten
/// el mismo valor no prueba el filtro: prueba que la consulta corre.
///
/// **Todas entran con la misma clave: `admin123`**, y el usuario es `usuario1`
/// hasta `usuario100`. Es un juego de prueba: la clave es igual para las cien a
/// propósito, para poder entrar con cualquiera sin ir a buscarla.
///
/// 🔴 Y por eso mismo: esto NO se usa fuera de un ambiente de prueba. Cien
/// cuentas con la misma clave conocida es exactamente lo que no se hace en
/// ningún lado donde haya datos de alguien.
///
/// ══ 🔴 DE DÓNDE SALEN ESTOS DATOS, Y POR QUÉ NO PUEDEN SALIR DE ACÁ ══
///
/// **Reconciliadas el 2026-09-04 con la cartera de prueba de notificaciones**, por pedido de
/// Juan: *«vamos a hacer que la app de Flutter de Collection tenga las identidades de los
/// cien que tenemos actualmente, con toda esa data»*.
///
/// El motivo es concreto: hasta hoy los dos sistemas tenían cien personas inventadas **cada
/// uno por separado, sin una sola cédula en común**. Medido: Collection tenía la cédula
/// `12137717` y notificaciones la `13185607`. Con juegos que no se cruzan no se puede probar
/// una integración de punta a punta — un envío que sale de acá no le llega a nadie de allá.
///
/// Ahora el `userId` de cada persona **es el mismo identificador con el que existe en
/// notificaciones**, así que las dos puntas hablan de la misma gente.
///
/// 🔴 **Y por eso mismo: estos nombres, cédulas, teléfonos y correos NO son inventados.**
/// Vienen de la cartera de desarrollo, y parecen de personas reales. Esta lista no puede
/// salir de un ambiente de prueba: no se compila en un APK que se distribuya, y ningún envío
/// de prueba puede dispararse contra estos teléfonos —son números que existen y cuestan
/// plata—. Contra el simulador de proveedor, o no se prueba.
///
/// El texto que estaba acá decía que las cédulas y los correos eran inventados. Dejarlo
/// habría sido una mentira en el código, del tipo que hace que alguien despliegue esto sin
/// pensarlo dos veces.
///
/// ## Los cuatro casos del modelo de identidad
///
/// Las cien de abajo son todas personas naturales con cédula — el caso de
/// siempre. Al final de este archivo hay CUATRO más, agregadas con el
/// rediseño de colecciones, que prueban lo que las cien no pueden: DOS
/// **empresas** (`TipoDeSujeto.juridica`, documento con `ClaseDeDocumento.rif`)
/// y DOS **empleados de un proveedor** (naturales, pero con [Organizacion] —
/// el sujeto PERTENECE a la organización, no se reemplaza por ella). Ver
/// [casosDeIdentidadDePrueba].
library;

import 'package:hz_collection_sdk/hz_collection_sdk.dart';

/// Una persona del juego de prueba.
class PersonaDePrueba {
  const PersonaDePrueba({
    required this.userId,
    required this.usuario,
    required this.cedula,
    required this.correo,
    required this.nombre,
    required this.sucursal,
    required this.ciudad,
    required this.plan,
    this.telefono = '',
    this.pais = '',
    this.estado = '',
    this.genero = '',
    this.tipo = TipoDeSujeto.natural,
    this.claseDeDocumento = ClaseDeDocumento.cedula,
    this.organizacion,
  });

  /// La clave con la que el comercio la identifica. Opaca para el SDK.
  ///
  /// En estas personas de prueba se compone a propósito —`usuario1-12137717`— en vez de ser
  /// un `u_9000` cualquiera: en la consola del proveedor se ve el identificador, y uno opaco
  /// obliga a ir a buscar de quién es cada vez. En un comercio de verdad será lo que él use.
  final String userId;

  /// Con qué entra: `usuario1` … `usuario100`. La contraseña es [claveDePrueba]
  /// para todas.
  final String usuario;

  // ── alias · se direcciona por acá ──────────────────────────────────────
  //
  // 🔴 El nombre del campo quedó de cuando sólo existían personas naturales.
  // Para los cuatro casos de [casosDeIdentidadDePrueba] guarda el número de
  // documento que corresponda —un RIF para las empresas—, y [claseDeDocumento]
  // dice cuál es. No se renombró el campo para no tocar las cien de abajo.
  final String cedula;
  final String correo;

  /// 🔴 EL TELÉFONO ES UN ALIAS, NO UN ATRIBUTO — y la diferencia no es de forma.
  ///
  /// Por acá se DIRECCIONA: es a dónde le llega un SMS o un WhatsApp, igual que el correo.
  /// Ponerlo entre los atributos lo dejaría para mostrar y filtrar, pero no para enviar — y
  /// el envío por teléfono es justamente lo que la integración con notificaciones tiene que
  /// poder probar.
  ///
  /// Vacío por omisión para no obligar a los cuatro casos del final a declararlo.
  final String telefono;

  // ── atributos · se filtra y se muestra por acá ─────────────────────────
  final String nombre;
  final String sucursal;
  final String ciudad;
  final String plan;

  /// Los tres que trajo la reconciliación. Son para filtrar: `estado` es el corte que de
  /// verdad reparte la cartera —veinte grupos, de 1 a 18 personas— mientras `ciudad` tiene
  /// cincuenta y dos valores y deja grupos de dos, que no prueban ningún filtro.
  final String pais;
  final String estado;
  final String genero;

  /// Si es una persona natural o una empresa. Por omisión, natural: es lo que
  /// son las cien de abajo.
  final TipoDeSujeto tipo;

  /// Con qué clase de documento se identifica [cedula]. Por omisión, cédula.
  final ClaseDeDocumento claseDeDocumento;

  /// La organización a la que pertenece, si tiene una. `null` en las cien:
  /// no todo el mundo trabaja para un proveedor del comercio.
  final Organizacion? organizacion;

  /// El documento tal como lo espera `AkPush.alIniciarSesion`. Se arma desde
  /// [cedula] y [claseDeDocumento]: son las dos empresas las que cambian la
  /// clase, no el campo — así el resto del demo no se entera de la diferencia.
  Documento get documento => Documento(clase: claseDeDocumento, numero: cedula);

  /// Lo que el backend del comercio le mandaría al servicio para darla de alta.
  Map<String, dynamic> get comoAlta => {
        'userId': userId,
        // El teléfono va entre los alias porque se direcciona por él. Los vacíos no viajan:
        // un alias en blanco no direcciona a nadie y ocuparía un lugar en el índice.
        'alias': {
          'cedula': cedula,
          'correo': correo,
          if (telefono.isNotEmpty) 'telefono': telefono,
        },
        'atributos': {
          'nombre': nombre,
          'sucursal': sucursal,
          'ciudad': ciudad,
          'plan': plan,
          if (pais.isNotEmpty) 'pais': pais,
          if (estado.isNotEmpty) 'estado': estado,
          if (genero.isNotEmpty) 'genero': genero,
        },
      };

  @override
  String toString() => '$usuario · $nombre · $cedula · $sucursal · $plan';
}

/// Las cien.
/// La contraseña de las cien. Igual para todas, a propósito y sólo para probar.
const claveDePrueba = 'admin123';

const cienPersonas = <PersonaDePrueba>[
  PersonaDePrueba(
    userId: '6693ea988b7b3a506c2aa58e',
    usuario: 'usuario1',
    cedula: '13185607',
    correo: 'murzilopezi@gmail.com',
    telefono: '+584247111443',
    nombre: 'Ivan Murzi Lopez',
    sucursal: 'MIR-01',
    pais: 'Venezuela',
    estado: 'Miranda',
    ciudad: 'Santa Teresa del Tuy',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '69bdbc5b5aa734219afed294',
    usuario: 'usuario2',
    cedula: '26051970',
    correo: 'linnetmontoya1208@gmail.com',
    telefono: '+584144944612',
    nombre: 'Linnet Montoya',
    sucursal: 'MCY-01',
    pais: 'Venezuela',
    estado: 'Aragua',
    ciudad: 'Maracay',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '676dc59e8cc125da8f90e289',
    usuario: 'usuario3',
    cedula: '17229393',
    correo: 'jesusloyo348@gmail.com',
    telefono: '+584123716221',
    nombre: 'Jesús Alexander Loyo Solís',
    sucursal: 'BQT-01',
    pais: 'Venezuela',
    estado: 'Lara',
    ciudad: 'Barquisimeto',
    genero: 'Masculino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '66f98738c5430b462e4999ba',
    usuario: 'usuario4',
    cedula: '18906519',
    correo: 'maricar5588@gmail.com',
    telefono: '+584143544954',
    nombre: 'Marielba Balza Zambrano',
    sucursal: 'BNS-01',
    pais: 'Venezuela',
    estado: 'Barinas',
    ciudad: 'Barinas',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '6a15bcfb937287c54ffa5835',
    usuario: 'usuario5',
    cedula: '20946420',
    correo: 'edapim12@gmail.com',
    telefono: '+584246691808',
    nombre: 'Erwin Daniel Pineda Morillo',
    sucursal: 'MCB-01',
    pais: 'Venezuela',
    estado: 'Zulia',
    ciudad: 'Maracaibo',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '67622ae828df99169d59004c',
    usuario: 'usuario6',
    cedula: '30379380',
    correo: 'luisahenriquez647@gmail.com',
    telefono: '+584247253332',
    nombre: 'Joelimar Brito',
    sucursal: 'CMN-01',
    pais: 'Venezuela',
    estado: 'Sucre',
    ciudad: 'Cumaná',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '685d9e58ceb7859159821503',
    usuario: 'usuario7',
    cedula: '28020186',
    correo: 'gonzalezjhonnar@gmail.com',
    telefono: '+584264552908',
    nombre: 'Jhonnar Alberto González Peña',
    sucursal: 'BQT-02',
    pais: 'Venezuela',
    estado: 'Lara',
    ciudad: 'Barquisimeto',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '663e58be853c3b3dda5b2cab',
    usuario: 'usuario8',
    cedula: '25358741',
    correo: 'barretocramon@gmail.com',
    telefono: '+584128411375',
    nombre: 'Ramon Celestino Barreto \\n',
    sucursal: 'BAR-01',
    pais: 'Venezuela',
    estado: 'Anzoátegui',
    ciudad: 'San José de Guanipa (El Tigrito)',
    genero: 'Masculino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '66bb8d8e9ae2ac1f4203fbae',
    usuario: 'usuario9',
    cedula: '5666835',
    correo: 'nancyczambrano@yahoo.es',
    telefono: '+584165020532',
    nombre: 'Nancy Zambrano Pantaleon',
    sucursal: 'SCR-01',
    pais: 'Venezuela',
    estado: 'Táchira',
    ciudad: 'San Cristobal',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '6792aeae4d4c4d051dcfca72',
    usuario: 'usuario10',
    cedula: '13937553',
    correo: 'irisjhoseptaa@gmail.com',
    telefono: '+584125450015',
    nombre: 'Iris Flores',
    sucursal: 'BNS-02',
    pais: 'Venezuela',
    estado: 'Barinas',
    ciudad: 'Barinas',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '69445173ca72813b8353cde1',
    usuario: 'usuario11',
    cedula: '28155206',
    correo: 'joemilcarrizales2@gmail.com',
    telefono: '+584241214852',
    nombre: 'Joemil Carrixales',
    sucursal: 'MIR-02',
    pais: 'Venezuela',
    estado: 'Miranda',
    ciudad: 'Baruta',
    genero: 'Masculino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '65ac4f589efc433b8da8cc56',
    usuario: 'usuario12',
    cedula: '26471003',
    correo: 'bracho488@gmail.com',
    telefono: '+584126831787',
    nombre: 'Luis Bracho Acosta',
    sucursal: 'MCB-02',
    pais: 'Venezuela',
    estado: 'Zulia',
    ciudad: 'San Francisco',
    genero: 'Masculino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '68c788fcad3fbbc0727010cd',
    usuario: 'usuario13',
    cedula: '13696845',
    correo: 'katerinbarrios49@gmail.com',
    telefono: '+584121553358',
    nombre: 'Katerin Katiuska Barrios',
    sucursal: 'SFE-01',
    pais: 'Venezuela',
    estado: 'Yaracuy',
    ciudad: 'Guama',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '680b64f7285c51d9d2f582d6',
    usuario: 'usuario14',
    cedula: '20343971',
    correo: 'elizabethguaita3@gmail.com',
    telefono: '+584264809921',
    nombre: 'Elizabeth Guaita Jiménez',
    sucursal: 'BAR-02',
    pais: 'Venezuela',
    estado: 'Anzoátegui',
    ciudad: 'Barcelona',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6928c5243fce7ec90e67b59f',
    usuario: 'usuario15',
    cedula: '16257974',
    correo: 'camd.2106@gmail.com',
    telefono: '+584248096242',
    nombre: 'Carlos Marcano',
    sucursal: 'VAL-01',
    pais: 'Venezuela',
    estado: 'Carabobo',
    ciudad: 'Valencia',
    genero: 'Masculino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '6a121f731231d3d7b1ccab7a',
    usuario: 'usuario16',
    cedula: '33374137',
    correo: 'angelicasandrea20@gmail.com',
    telefono: '+584246933611',
    nombre: 'Angelica Sandrea',
    sucursal: 'MCB-03',
    pais: 'Venezuela',
    estado: 'Zulia',
    ciudad: 'Cabimas',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '659d5a4e19fe66249ffdc827',
    usuario: 'usuario17',
    cedula: '19316726',
    correo: 'jsmejia70@gmail.com',
    telefono: '+584120422179',
    nombre: 'Jose Mejias Nolasco',
    sucursal: 'CCS-01',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '696ae20fcd6f6e2834177f07',
    usuario: 'usuario18',
    cedula: '32756463',
    correo: 'paolafiguera840@gmail.com',
    telefono: '+584160293123',
    nombre: 'Paola Figuera',
    sucursal: 'LGU-01',
    pais: 'Venezuela',
    estado: 'La Guaira',
    ciudad: 'Catia La Mar',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '672d2c38aa6a03e2727a85cd',
    usuario: 'usuario19',
    cedula: '24206416',
    correo: 'anaidysmujica120@gmail.com',
    telefono: '+584126668935',
    nombre: 'Anaidys Mujica',
    sucursal: 'CRO-01',
    pais: 'Venezuela',
    estado: 'Falcón',
    ciudad: 'Punto Fijo',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '6949bc42ca72813b83ab4367',
    usuario: 'usuario20',
    cedula: '18484854',
    correo: 'mayelisgauna03@gmail.com',
    telefono: '+584262196335',
    nombre: 'Mayelis Del Carmen Gauna Cardozo',
    sucursal: 'CCS-02',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '67eb0f7bbee4d26ad9816b57',
    usuario: 'usuario21',
    cedula: '31456967',
    correo: 'machadoroblesmariana@gmail.com',
    telefono: '+584244139646',
    nombre: 'Mariana Machado',
    sucursal: 'VAL-02',
    pais: 'Venezuela',
    estado: 'Carabobo',
    ciudad: 'Valencia',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '6a297bf1ddca792936ec3eb8',
    usuario: 'usuario22',
    cedula: '24680346',
    correo: 'aikerantonioviscayaguedez@gmail.com',
    telefono: '+584245765376',
    nombre: 'Aiker Antonio Viscaya Guedez',
    sucursal: 'BQT-03',
    pais: 'Venezuela',
    estado: 'Lara',
    ciudad: 'Barquisimeto',
    genero: 'Masculino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '68ec266a8483d77de766c16a',
    usuario: 'usuario23',
    cedula: '27529936',
    correo: 'anabelamarcantonio@gmail.com',
    telefono: '+584121531319',
    nombre: 'Anabela Marcantonio',
    sucursal: 'SFE-02',
    pais: 'Venezuela',
    estado: 'Yaracuy',
    ciudad: 'Independencia',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '6712665ef4fd75e6af0a296b',
    usuario: 'usuario24',
    cedula: '18834902',
    correo: 'farfan.edgareduardo@gmail.com',
    telefono: '+584127450200',
    nombre: 'Edgar Farfan',
    sucursal: 'SJM-01',
    pais: 'Venezuela',
    estado: 'Guárico',
    ciudad: 'Valle de La Pascua',
    genero: 'Masculino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '68cdc84ac2cca96f1db0107c',
    usuario: 'usuario25',
    cedula: '5700849',
    correo: 'malengo1958@gmail.com',
    telefono: '+584167155248',
    nombre: 'Maria Diaz',
    sucursal: 'CCS-03',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '67fb0503e2974ab77ee51d5a',
    usuario: 'usuario26',
    cedula: '20082649',
    correo: 'solianytorres12@gmail.com',
    telefono: '+584244198681',
    nombre: 'Iralic Rodriguez',
    sucursal: 'VAL-03',
    pais: 'Venezuela',
    estado: 'Carabobo',
    ciudad: 'Guigue',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '688bc6d7158050eb713b88d7',
    usuario: 'usuario27',
    cedula: '15379713',
    correo: 'lyrondon.2014@gmail.com',
    telefono: '+584142358278',
    nombre: 'Luz Rondon',
    sucursal: 'CCS-01',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '665a41e782af16211f0bcc64',
    usuario: 'usuario28',
    cedula: '12783874',
    correo: 'jessikah0220@gmail.com',
    telefono: '+584241642887',
    nombre: 'Jessika Yuslemis Hernandez Dugarte',
    sucursal: 'CCS-02',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '681103593106f27739ff30e4',
    usuario: 'usuario29',
    cedula: '26522095',
    correo: 'endimarodriguez@gmail.com',
    telefono: '+584124920840',
    nombre: 'Endimar Rodríguez',
    sucursal: 'MCB-01',
    pais: 'Venezuela',
    estado: 'Zulia',
    ciudad: 'Ciudad Ojeda',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '69a3309a706de03c9473deab',
    usuario: 'usuario30',
    cedula: '15111557',
    correo: 'pedrolanza00@gmail.com',
    telefono: '+584127009429',
    nombre: 'Pedro Lanza',
    sucursal: 'CMN-02',
    pais: 'Venezuela',
    estado: 'Sucre',
    ciudad: 'Cumaná',
    genero: 'Masculino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6577568df87e9d1c9b454a5e',
    usuario: 'usuario31',
    cedula: '14130610',
    correo: 'karh.cake@gmail.com',
    telefono: '+584242875889',
    nombre: 'Angy Barrios Mendez',
    sucursal: 'CCS-03',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '6854d6760a9f1ab9644af83f',
    usuario: 'usuario32',
    cedula: '15509528',
    correo: 'yoanarondon120@gmail.com',
    telefono: '+584123798716',
    nombre: 'Yoana Rondón',
    sucursal: 'BAR-03',
    pais: 'Venezuela',
    estado: 'Anzoátegui',
    ciudad: 'San Tomé',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '6839cb64ef3c3c33f6f9e6b4',
    usuario: 'usuario33',
    cedula: '17217406',
    correo: 'sanchez.02nacho@gmail.com',
    telefono: '+584127584089',
    nombre: 'Ignacio Sánchez',
    sucursal: 'CBL-01',
    pais: 'Venezuela',
    estado: 'Bolívar',
    ciudad: 'Ciudad Guayana',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '6a4bdba5cb2773722d9e8e28',
    usuario: 'usuario34',
    cedula: '13152829',
    correo: 'luisr.vegasv@gmail.com',
    telefono: '+584242659780',
    nombre: 'Luis Vegas',
    sucursal: 'SJM-02',
    pais: 'Venezuela',
    estado: 'Guárico',
    ciudad: 'San Juan de Los Morros',
    genero: 'Masculino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6797ff4cc7a3470d6ba47163',
    usuario: 'usuario35',
    cedula: '17000843',
    correo: 'maribel.vg7@yahoo.com',
    telefono: '+584142958206',
    nombre: 'Maribel Del Valle Vasquez Gutierrez',
    sucursal: 'SJM-03',
    pais: 'Venezuela',
    estado: 'Guárico',
    ciudad: 'Valle de La Pascua',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '675ce9113c745658586583f7',
    usuario: 'usuario36',
    cedula: '28628972',
    correo: 'franyoliscampos5@gmail.com',
    telefono: '+584248321946',
    nombre: 'Franyolis Campos',
    sucursal: 'BAR-01',
    pais: 'Venezuela',
    estado: 'Anzoátegui',
    ciudad: 'Barcelona',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '67d60cc742e7ba716da000cb',
    usuario: 'usuario37',
    cedula: '20716496',
    correo: 'garciscarlos@gmail.com',
    telefono: '+584140638517',
    nombre: 'Carlos David García',
    sucursal: 'SCR-02',
    pais: 'Venezuela',
    estado: 'Táchira',
    ciudad: 'La Grita',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '67ca44a97c760bdc3a1316ad',
    usuario: 'usuario38',
    cedula: '11390011',
    correo: 'saavedraluis63@gmail.com',
    telefono: '+584125643996',
    nombre: 'Luis Antonio Saavedra Virla',
    sucursal: 'MCB-02',
    pais: 'Venezuela',
    estado: 'Zulia',
    ciudad: 'San Francisco',
    genero: 'Masculino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6789969f4d4c4d051db2b86e',
    usuario: 'usuario39',
    cedula: '30223978',
    correo: 'sina.silano21@gmail.com',
    telefono: '+584128405227',
    nombre: 'Siandry Silano',
    sucursal: 'BAR-02',
    pais: 'Venezuela',
    estado: 'Anzoátegui',
    ciudad: 'Barcelona',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '680bf4c1ad0d735311e0cd65',
    usuario: 'usuario40',
    cedula: '16031844',
    correo: 'jordanlo3915@gmail.com',
    telefono: '+584242716874',
    nombre: 'Gordan Hernández',
    sucursal: 'CCS-01',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Masculino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '647a2b2289532a071f7727f7',
    usuario: 'usuario41',
    cedula: '26466407',
    correo: 'orianagarcial2801@gmail.com',
    telefono: '+584241484353',
    nombre: 'Oriana Garcia Larrua',
    sucursal: 'CCS-02',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '69431554d1ba073bd746201d',
    usuario: 'usuario42',
    cedula: '27760662',
    correo: 'julianmartinez.uenza@gmail.com',
    telefono: '+584165378775',
    nombre: 'Julian Martinez',
    sucursal: 'BQT-01',
    pais: 'Venezuela',
    estado: 'Lara',
    ciudad: 'Barquisimeto',
    genero: 'Masculino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '66203339995421486318e002',
    usuario: 'usuario43',
    cedula: '27287499',
    correo: 'vittoriosodaniela@gmail.com',
    telefono: '+584242751755',
    nombre: 'Daniela Vittorioso Salazar',
    sucursal: 'MIR-03',
    pais: 'Venezuela',
    estado: 'Miranda',
    ciudad: 'Los Teques',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '68fa9f6989346971bf71639f',
    usuario: 'usuario44',
    cedula: '10691263',
    correo: 'mariluguarini@gmail.com',
    telefono: '+584142618474',
    nombre: 'Marilu Guarini Rodriguez',
    sucursal: 'MIR-01',
    pais: 'Venezuela',
    estado: 'Miranda',
    ciudad: 'Guarenas',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '67e813886ec1c43338f8c702',
    usuario: 'usuario45',
    cedula: '17473766',
    correo: 'yordinzambrano17@gmail.com',
    telefono: '+584241956113',
    nombre: 'Yordin Zambrano',
    sucursal: 'MIR-02',
    pais: 'Venezuela',
    estado: 'Miranda',
    ciudad: 'San Francisco de Yare',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '693505eeb5314d04cee34e14',
    usuario: 'usuario46',
    cedula: '32077422',
    correo: 'perazafabiana14@gmail.com',
    telefono: '+584145684035',
    nombre: 'Fabiana Peraza',
    sucursal: 'BQT-02',
    pais: 'Venezuela',
    estado: 'Lara',
    ciudad: 'Barquisimeto',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6697e33c6ed9b64dbd7857d7',
    usuario: 'usuario47',
    cedula: '13750276',
    correo: 'duranyris15@gmail.com',
    telefono: '+584142155883',
    nombre: 'Yris Del Valle Duran De Uribe',
    sucursal: 'CCS-03',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '68dc560041477e8046903ac2',
    usuario: 'usuario48',
    cedula: '23899737',
    correo: 'yosesalazar39@gmail.com',
    telefono: '+584249331463',
    nombre: 'Yoseline Salazar',
    sucursal: 'MTR-01',
    pais: 'Venezuela',
    estado: 'Monagas',
    ciudad: 'Maturín',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '67fc541eed3cba680c12e408',
    usuario: 'usuario49',
    cedula: '10380221',
    correo: 'nelsont284@gmail.com',
    telefono: '+584141221314',
    nombre: 'Nelson Torres',
    sucursal: 'CCS-01',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '67df0db1f16348cef233ad56',
    usuario: 'usuario50',
    cedula: '31604511',
    correo: 'cm347921@gmail.com',
    telefono: '+584124325094',
    nombre: 'Carlos Martinez',
    sucursal: 'BAR-03',
    pais: 'Venezuela',
    estado: 'Anzoátegui',
    ciudad: 'El Tigre',
    genero: 'Masculino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '68261b8531a6ea08549fbaee',
    usuario: 'usuario51',
    cedula: '18607458',
    correo: 'consuelocastillo753@gmail.com',
    telefono: '+584246909168',
    nombre: 'Eunimer Castillo',
    sucursal: 'CRO-02',
    pais: 'Venezuela',
    estado: 'Falcón',
    ciudad: 'Coro',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '67feed86afd168e5627b91e0',
    usuario: 'usuario52',
    cedula: '19064199',
    correo: 'natashaseijasa@gmail.com',
    telefono: '+584241356509',
    nombre: 'Natasha Seijas',
    sucursal: 'CCS-02',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '6a4f1416063573f5ea76a809',
    usuario: 'usuario53',
    cedula: '17596892',
    correo: 'juancarlosbecerra477@gmail.com',
    telefono: '+584120165853',
    nombre: 'Juan Becerra',
    sucursal: 'CCS-03',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '675e23a78358510506d9e042',
    usuario: 'usuario54',
    cedula: '13654994',
    correo: 'gmfsantil2020@gmail.com',
    telefono: '+584168918026',
    nombre: 'Fernando Garcia',
    sucursal: 'MTR-02',
    pais: 'Venezuela',
    estado: 'Monagas',
    ciudad: 'Maturín',
    genero: 'Masculino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6740d6fecfe44d4341921bd3',
    usuario: 'usuario55',
    cedula: '11100093',
    correo: 'dilciamercedesmoreno@gmail.com',
    telefono: '+584127011255',
    nombre: 'Dilcia Mercedes Moreno Gonzales',
    sucursal: 'VAL-01',
    pais: 'Venezuela',
    estado: 'Carabobo',
    ciudad: 'El Palito',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '68e906e1a46baed36b8a70eb',
    usuario: 'usuario56',
    cedula: '18214423',
    correo: 'gd884488@gmail.com',
    telefono: '+584165334167',
    nombre: 'Mercedes Gómez',
    sucursal: 'CMN-03',
    pais: 'Venezuela',
    estado: 'Sucre',
    ciudad: 'Tunapuy',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '67f6b5bbf4312d7d122cd5c4',
    usuario: 'usuario57',
    cedula: '23505498',
    correo: 'yanirislaprincerondon@hotmail.com',
    telefono: '+584148651314',
    nombre: 'Yaniris Rondon',
    sucursal: 'CBL-02',
    pais: 'Venezuela',
    estado: 'Bolívar',
    ciudad: 'Ciudad Guayana',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '6980d9350bf8d4e62b83b9eb',
    usuario: 'usuario58',
    cedula: '13637588',
    correo: 'bernardinosan584@gmail.com',
    telefono: '+584125126135',
    nombre: 'Ysbelis Antuarez',
    sucursal: 'CCS-01',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '68d8b9ccda379f27664eb3ee',
    usuario: 'usuario59',
    cedula: '26008346',
    correo: 'zambranozorianny@gmail.com',
    telefono: '+584124446697',
    nombre: 'Zorismar Zambrano Ortega',
    sucursal: 'SJM-01',
    pais: 'Venezuela',
    estado: 'Guárico',
    ciudad: 'Valle de La Pascua',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '6a3ac678f89b876dd94fe271',
    usuario: 'usuario60',
    cedula: '26049396',
    correo: 'ivannyyanez@gmail.com',
    telefono: '+584125082721',
    nombre: 'Ivanny Yanez',
    sucursal: 'BQT-03',
    pais: 'Venezuela',
    estado: 'Lara',
    ciudad: 'Barquisimeto',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '69a428f5c4bf6edbfaefbdef',
    usuario: 'usuario61',
    cedula: '27798524',
    correo: 'lss4nch3z3@gmail.com',
    telefono: '+584123071137',
    nombre: 'Luis Sánchez',
    sucursal: 'CCS-02',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'El Junquito',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '66004850dcd2bc2cce29733a',
    usuario: 'usuario62',
    cedula: '26181365',
    correo: 'erick-120_@gmail.com',
    telefono: '+584121429211',
    nombre: 'Erick Gonzalez Molleja',
    sucursal: 'BQT-01',
    pais: 'Venezuela',
    estado: 'Lara',
    ciudad: 'Cabudare',
    genero: 'Masculino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '675c950a02dc7d36ba0d0207',
    usuario: 'usuario63',
    cedula: '15877472',
    correo: 'dennisreyesparroco@gmail.com',
    telefono: '+584121117437',
    nombre: 'Dennis Reyes',
    sucursal: 'MTR-03',
    pais: 'Venezuela',
    estado: 'Monagas',
    ciudad: 'Aragua de Maturín',
    genero: 'Masculino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '690693c389346971bfe9ff8f',
    usuario: 'usuario64',
    cedula: '23390900',
    correo: 'dayrerodriguez743@gmail.com',
    telefono: '+584247350891',
    nombre: 'Dayre Yorlet Rodriquez Angulo',
    sucursal: 'MER-01',
    pais: 'Venezuela',
    estado: 'Mérida',
    ciudad: 'Ejido',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '69ebfdd62631ba1bc0fc0e42',
    usuario: 'usuario65',
    cedula: '27987247',
    correo: 'rpaola1827@gmail.com',
    telefono: '+584245642340',
    nombre: 'Paola Rodriguez',
    sucursal: 'BQT-02',
    pais: 'Venezuela',
    estado: 'Lara',
    ciudad: 'Tintorero',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '67179928e8ec37a7fc4e7ec4',
    usuario: 'usuario66',
    cedula: '6882580',
    correo: 'freymg@gmail.com',
    telefono: '+584127720561',
    nombre: 'Omaira Sanchez',
    sucursal: 'VAL-02',
    pais: 'Venezuela',
    estado: 'Carabobo',
    ciudad: 'Campo de Carabobo',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6768389e4d2846814fd36c0a',
    usuario: 'usuario67',
    cedula: '17005038',
    correo: 'yennifermariabelliosanchez@gmail.com',
    telefono: '+584127337398',
    nombre: 'Yennifer Bellio',
    sucursal: 'MCB-03',
    pais: 'Venezuela',
    estado: 'Zulia',
    ciudad: 'Los Puertos de Altagracia',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '64f38328e0cd400e855989c9',
    usuario: 'usuario68',
    cedula: '14163407',
    correo: 'yaksimontebugnoli@gmail.com',
    telefono: '+584241758469',
    nombre: 'Yaksi Castillo Lopenza',
    sucursal: 'LGU-02',
    pais: 'Venezuela',
    estado: 'La Guaira',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '6a04f1b80ad994d79144bee0',
    usuario: 'usuario69',
    cedula: '13959432',
    correo: 'fredenry2015@gmail.com',
    telefono: '+584122515145',
    nombre: 'Freddy Perez',
    sucursal: 'GUA-01',
    pais: 'Venezuela',
    estado: 'Portuguesa',
    ciudad: 'Guanare',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '693d68d2ca72813b83d2ccbf',
    usuario: 'usuario70',
    cedula: '20141856',
    correo: 'fidelabustamantej@gmail.com',
    telefono: '+584247400399',
    nombre: 'Fidel Bustamante',
    sucursal: 'MER-02',
    pais: 'Venezuela',
    estado: 'Mérida',
    ciudad: 'El Vigía',
    genero: 'Masculino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '66cc25aaad61834f68ade4d5',
    usuario: 'usuario71',
    cedula: '12955856',
    correo: 'yurelkichirinos@gmail.com',
    telefono: '+584242874455',
    nombre: 'Yurelki Margarita Chirinos Meléndez',
    sucursal: 'CCS-03',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '691ce85675c7e43b8dcbe021',
    usuario: 'usuario72',
    cedula: '14654707',
    correo: 'albertopaezwillian0031@gmail.com',
    telefono: '+584246702745',
    nombre: 'Willian Paez',
    sucursal: 'CRO-03',
    pais: 'Venezuela',
    estado: 'Falcón',
    ciudad: 'Coro',
    genero: 'Masculino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '679c22aa064cc307eaace1c9',
    usuario: 'usuario73',
    cedula: '22388130',
    correo: '12-10330@usb.ve',
    telefono: '+584129708654',
    nombre: 'Juan Carlos Cisneros',
    sucursal: 'MIR-03',
    pais: 'Venezuela',
    estado: 'Miranda',
    ciudad: 'Baruta',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '6962b114ecf499fbbafc2286',
    usuario: 'usuario74',
    cedula: '18152040',
    correo: 'polancoyurmeryyp@gmail.com',
    telefono: '+584146150778',
    nombre: 'Yurmery Carolina Polanco Valles',
    sucursal: 'CRO-01',
    pais: 'Venezuela',
    estado: 'Falcón',
    ciudad: 'Coro',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '67a2840d5e96342af1b6c3aa',
    usuario: 'usuario75',
    cedula: '31383561',
    correo: 'greikervasquez15@gmail.com',
    telefono: '+584121830708',
    nombre: 'Greiker Vasquez',
    sucursal: 'MIR-01',
    pais: 'Venezuela',
    estado: 'Miranda',
    ciudad: 'Charallave',
    genero: 'Masculino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '6a2fe62d08274b6e49f44f39',
    usuario: 'usuario76',
    cedula: '19199995',
    correo: 'mariediaz989@gmail.com',
    telefono: '+584241290652',
    nombre: 'Mariela Diaz',
    sucursal: 'MER-03',
    pais: 'Venezuela',
    estado: 'Mérida',
    ciudad: 'La Blanca (12 de Octubre)',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '64ecada921538a4a993da5d7',
    usuario: 'usuario77',
    cedula: '16058591',
    correo: 'marfer1703@gmail.com',
    telefono: '+584162107735',
    nombre: 'Maria Lobeto Gonzalez',
    sucursal: 'CCS-01',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '69e405ec66eb3db1872a24fd',
    usuario: 'usuario78',
    cedula: '25100122',
    correo: 'reinaldojcc256@gmail.com',
    telefono: '+584141895712',
    nombre: 'Reinaldo Castañeda',
    sucursal: 'CMN-01',
    pais: 'Venezuela',
    estado: 'Sucre',
    ciudad: 'Cumaná',
    genero: 'Masculino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6a398dbfddca7929367b704e',
    usuario: 'usuario79',
    cedula: '24225759',
    correo: 'yurbelyshernandez23@gmail.com',
    telefono: '+584125579498',
    nombre: 'Yurbelys Hernández',
    sucursal: 'MCY-02',
    pais: 'Venezuela',
    estado: 'Aragua',
    ciudad: 'Santa Rita',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '67e569b88052fd21e891dd55',
    usuario: 'usuario80',
    cedula: '20112974',
    correo: 'jesusitaguerra2020@gmail.com',
    telefono: '+584147853481',
    nombre: 'Jesusita Del Valle Guerra Rivas',
    sucursal: 'CMN-02',
    pais: 'Venezuela',
    estado: 'Sucre',
    ciudad: 'Cumaná',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '6a0772ae0ad994d7915c9d48',
    usuario: 'usuario81',
    cedula: '30994948',
    correo: 'fransheskabrito27@gmail.com',
    telefono: '+584248867680',
    nombre: 'Fransheska Brito',
    sucursal: 'BAR-01',
    pais: 'Venezuela',
    estado: 'Anzoátegui',
    ciudad: 'El Tigre',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '6757b231a62ff256ea4465b3',
    usuario: 'usuario82',
    cedula: '4431392',
    correo: 'erciliaram.28@gmail.com',
    telefono: '+584247295187',
    nombre: 'Ercilia Calderón',
    sucursal: 'TRU-01',
    pais: 'Venezuela',
    estado: 'Trujillo',
    ciudad: 'Valera',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6758ad97a62ff256ea48f5a9',
    usuario: 'usuario83',
    cedula: '20126449',
    correo: 'carlos_gaglio@hotmail.com',
    telefono: '+584248161028',
    nombre: 'Carlos Leonardo Gaglio Maiz',
    sucursal: 'CMN-03',
    pais: 'Venezuela',
    estado: 'Sucre',
    ciudad: 'Cariaco',
    genero: 'Masculino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '65f5d67dde1b497b598f2307',
    usuario: 'usuario84',
    cedula: '14047855',
    correo: 'vianneyveliz6@gmail.com',
    telefono: '+584249009511',
    nombre: 'Vianney Veliz \\n',
    sucursal: 'MTR-01',
    pais: 'Venezuela',
    estado: 'Monagas',
    ciudad: 'Maturín',
    genero: 'Femenino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '65f0486bee4a396c3a6d76cf',
    usuario: 'usuario85',
    cedula: '18557658',
    correo: 'carolina.leidy@yahoo.com.be',
    telefono: '+584241086254',
    nombre: 'Leidy Jaimes Cuauro',
    sucursal: 'CCS-02',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '67e59c738052fd21e8933f5f',
    usuario: 'usuario86',
    cedula: '16456734',
    correo: 'quervis.nelson@dsg.luz.edu.ve',
    telefono: '+584246276621',
    nombre: 'Quervis Jose Nelson Díaz',
    sucursal: 'MCB-01',
    pais: 'Venezuela',
    estado: 'Zulia',
    ciudad: 'Maracaibo',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '67070001958c6619afbc2d22',
    usuario: 'usuario87',
    cedula: '16023864',
    correo: 'michebermudes@gmail.com',
    telefono: '+584121303060',
    nombre: 'Michelle Bermúdez',
    sucursal: 'VAL-03',
    pais: 'Venezuela',
    estado: 'Carabobo',
    ciudad: 'Valencia',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '6763204d4d2846814fb29906',
    usuario: 'usuario88',
    cedula: '20696925',
    correo: 'miguelagp2601@gmail.com',
    telefono: '+584144284978',
    nombre: 'Miguel Andres Gomez Palencia',
    sucursal: 'VAL-01',
    pais: 'Venezuela',
    estado: 'Carabobo',
    ciudad: 'Valencia',
    genero: 'Masculino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '68b0d4fe5ae228d462de6c79',
    usuario: 'usuario89',
    cedula: '30239870',
    correo: 'darlinramoss2025@gmail.com',
    telefono: '+584241709508',
    nombre: 'Darlin Ramos',
    sucursal: 'CCS-03',
    pais: 'Venezuela',
    estado: 'Distrito Capital',
    ciudad: 'Caracas',
    genero: 'Femenino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '693c45e2ca72813b83c516fc',
    usuario: 'usuario90',
    cedula: '23503890',
    correo: 'mariangiangeli28@gmail.com',
    telefono: '+584149885271',
    nombre: 'Mariangi Angeli',
    sucursal: 'CBL-03',
    pais: 'Venezuela',
    estado: 'Bolívar',
    ciudad: 'Ciudad Guayana',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6869811da60c0fff144868f2',
    usuario: 'usuario91',
    cedula: '29655486',
    correo: 'sofiasantamaria010203@gmail.com',
    telefono: '+584128769794',
    nombre: 'Sofía Santamaría',
    sucursal: 'BAR-02',
    pais: 'Venezuela',
    estado: 'Anzoátegui',
    ciudad: 'Puerto La Cruz',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '69add42549ea025f0ddce6d4',
    usuario: 'usuario92',
    cedula: '22651009',
    correo: 'josezabala817@gmail.com',
    telefono: '+584122974494',
    nombre: 'Jose Zabala',
    sucursal: 'PLC-01',
    pais: 'Venezuela',
    estado: 'Nueva Esparta',
    ciudad: 'La Guardia',
    genero: 'Masculino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '676eb0294d2846814ff254ff',
    usuario: 'usuario93',
    cedula: '27481716',
    correo: 'gzambrano2306@gmail.com',
    telefono: '+584244443278',
    nombre: 'Gabriel Zambrano',
    sucursal: 'VAL-02',
    pais: 'Venezuela',
    estado: 'Carabobo',
    ciudad: 'Valencia',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '66e205b1d3a22a4853d5a573',
    usuario: 'usuario94',
    cedula: '18094733',
    correo: 'krisbellcastro2020@gmail.com',
    telefono: '+584126146513',
    nombre: 'Krisbell Castro',
    sucursal: 'VAL-03',
    pais: 'Venezuela',
    estado: 'Carabobo',
    ciudad: 'Valencia',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '6860619cceb78591599439c3',
    usuario: 'usuario95',
    cedula: '23945304',
    correo: 'juricarluna@gmail.com',
    telefono: '+584129135206',
    nombre: 'Juricar Luna',
    sucursal: 'CMN-01',
    pais: 'Venezuela',
    estado: 'Sucre',
    ciudad: 'Carúpano',
    genero: 'Femenino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '67732b8a4d4c4d051d72dae8',
    usuario: 'usuario96',
    cedula: '26592049',
    correo: 'magusmeudon@gmail.com',
    telefono: '+584241206945',
    nombre: 'Magus Meudon',
    sucursal: 'CMN-02',
    pais: 'Venezuela',
    estado: 'Sucre',
    ciudad: 'Cumaná',
    genero: 'Masculino',
    plan: 'Empleados',
  ),
  PersonaDePrueba(
    userId: '67644bdc4d4c4d051d22a5c2',
    usuario: 'usuario97',
    cedula: '14251035',
    correo: 'jimenezjr25@gmail.com',
    telefono: '+584129135257',
    nombre: 'Joel Reyes',
    sucursal: 'VAL-01',
    pais: 'Venezuela',
    estado: 'Carabobo',
    ciudad: 'Valencia',
    genero: 'Masculino',
    plan: 'Bronce',
  ),
  PersonaDePrueba(
    userId: '67a66ee90bb093d3aeea4cad',
    usuario: 'usuario98',
    cedula: '12289642',
    correo: 'rodriguezrosangeldelvalle07@gmail.com',
    telefono: '+584120603594',
    nombre: 'Rosangel Delvalle Rodriguez Gonzalez',
    sucursal: 'CMN-03',
    pais: 'Venezuela',
    estado: 'Sucre',
    ciudad: 'Carúpano',
    genero: 'Femenino',
    plan: 'Plata',
  ),
  PersonaDePrueba(
    userId: '683206548c328a7240ea4b9e',
    usuario: 'usuario99',
    cedula: '19829092',
    correo: 'fredpalacios6@gmail.com',
    telefono: '+584142867307',
    nombre: 'Fred David Palacios Flores',
    sucursal: 'MIR-02',
    pais: 'Venezuela',
    estado: 'Miranda',
    ciudad: 'Ocumare del Tuy',
    genero: 'Masculino',
    plan: 'Oro',
  ),
  PersonaDePrueba(
    userId: '67193ff4f4fd75e6af1bf0cd',
    usuario: 'usuario100',
    cedula: '13681536',
    correo: 'nestorherrera044@gmail.com',
    telefono: '+584121428155',
    nombre: 'Nestor Herrera',
    sucursal: 'SJM-02',
    pais: 'Venezuela',
    estado: 'Guárico',
    ciudad: 'El Socorro',
    genero: 'Masculino',
    plan: 'Empleados',
  ),
];

// ── Atajos para armar pruebas sin recorrer la lista a mano ────────────────

/// Las sucursales que existen en el juego de prueba, ordenadas.
List<String> get sucursalesDePrueba =>
    (cienPersonas.map((p) => p.sucursal).toSet().toList()..sort());

/// Los planes que existen.
List<String> get planesDePrueba =>
    (cienPersonas.map((p) => p.plan).toSet().toList()..sort());

/// Las de una sucursal. Para probar el envío segmentado.
List<PersonaDePrueba> deLaSucursal(String sucursal) =>
    cienPersonas.where((p) => p.sucursal == sucursal).toList();

/// Las de un plan.
List<PersonaDePrueba> delPlan(String plan) =>
    cienPersonas.where((p) => p.plan == plan).toList();

/// Buscar por cédula, que es el caso de uso que motivó todo el modelo de alias:
/// el emisor conoce la cédula y no el `userId`.
PersonaDePrueba? porCedula(String cedula) {
  for (final p in cienPersonas) {
    if (p.cedula == cedula) return p;
  }
  return null;
}

/// Entrar como la enésima. `porUsuario('usuario7')` o `laNumero(7)` — lo mismo.
PersonaDePrueba? porUsuario(String usuario) {
  for (final p in cienPersonas) {
    if (p.usuario == usuario) return p;
  }
  return null;
}

/// La enésima, de 1 a 100.
PersonaDePrueba? laNumero(int n) =>
    (n < 1 || n > cienPersonas.length) ? null : cienPersonas[n - 1];

/// Buscar por parecido en el nombre, que es lo que hace la consola.
List<PersonaDePrueba> buscarPorNombre(String texto) {
  final t = texto.trim().toLowerCase();
  if (t.isEmpty) return const [];
  return cienPersonas
      .where((p) => p.nombre.toLowerCase().contains(t))
      .toList();
}

// ── Los cuatro casos del modelo de identidad ───────────────────────────────
//
// Van APARTE de las cien, no mezclados adentro: [cienPersonas] promete cien
// personas naturales con cédula desde su propio nombre y su comentario, y
// agregar acá cuatro entradas de otra forma lo volvería falso para quien lo
// lea sin mirar el final del archivo. `main.dart` junta las dos listas para
// que las cuatro sean seleccionables en la pantalla del demo.

/// Dos empresas — `TipoDeSujeto.juridica`, con RIF.
const empresasDePrueba = <PersonaDePrueba>[
  PersonaDePrueba(
    userId: 'empresa1-J304521679',
    usuario: 'empresa1',
    cedula: 'J-304521679',
    correo: 'compras@distribuidoraelfaro.com.ve',
    nombre: 'Distribuidora El Faro, C.A.',
    sucursal: 'CCS-01',
    ciudad: 'Caracas',
    plan: 'Empresas',
    tipo: TipoDeSujeto.juridica,
    claseDeDocumento: ClaseDeDocumento.rif,
  ),
  PersonaDePrueba(
    userId: 'empresa2-J403187745',
    usuario: 'empresa2',
    cedula: 'J-403187745',
    correo: 'administracion@construval.com.ve',
    nombre: 'Construval Ingeniería, C.A.',
    sucursal: 'VAL-02',
    ciudad: 'Valencia',
    plan: 'Empresas',
    tipo: TipoDeSujeto.juridica,
    claseDeDocumento: ClaseDeDocumento.rif,
  ),
];

/// Dos empleados de un proveedor — naturales, con [Organizacion]. El sujeto
/// PERTENECE a la organización, no se reemplaza por ella: sigue teniendo su
/// propia cédula y su propio `userId`.
const empleadosDeProveedorDePrueba = <PersonaDePrueba>[
  PersonaDePrueba(
    userId: 'empleado1-19988341',
    usuario: 'empleado1',
    cedula: '19988341',
    correo: 'jgimenez@logisticasur.com.ve',
    nombre: 'Julio Giménez',
    sucursal: 'MCB-02',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
    organizacion: Organizacion(
      codigo: 'prov-logisticasur',
      nombre: 'Logística Sur, C.A.',
      rol: 'repartidor',
    ),
  ),
  PersonaDePrueba(
    userId: 'empleado2-20214477',
    usuario: 'empleado2',
    cedula: '20214477',
    correo: 'mtovar@logisticasur.com.ve',
    nombre: 'Mariana Tovar',
    sucursal: 'MCB-02',
    ciudad: 'Maracaibo',
    plan: 'Empleados',
    organizacion: Organizacion(
      codigo: 'prov-logisticasur',
      nombre: 'Logística Sur, C.A.',
      rol: 'supervisora',
    ),
  ),
];

/// Las cuatro juntas, para ofrecerlas en la pantalla del demo junto con las
/// cien. Ver la nota de arriba sobre por qué no van adentro de [cienPersonas].
const casosDeIdentidadDePrueba = <PersonaDePrueba>[
  ...empresasDePrueba,
  ...empleadosDeProveedorDePrueba,
];
